### ISSUE TITLE
Add options to customize the keyboard shortcuts

### ISSUE THREAD

**Issue by fturcheti** [fiatjaf/firefox-pinboard#8]

**Comment by fiatjaf** [comment]
Are you unsatisfied with the keyboard shortcuts?

**Comment by fturcheti** [comment]
No, they are fine for my taste, I was just thinking about giving more flexibility to the extension. I like when extensions provide these options because shortcuts overlapping is quite common, and annoying.

But I don't think this enhancement is "essential", just a welcome extra functionality, an idea for further improvement.

**Comment by fturcheti** [comment]
This does not make sense anymore, now that Firefox has a global manager for extension shortcuts.
