### ISSUE TITLE
Add option to define the action after bookmarking

### ISSUE THREAD

**Issue by fturcheti** [fiatjaf/firefox-pinboard#9]
Something like: "After saving bookmark: [Redirect to Pinboard home, Close the popup]"

**Comment by fiatjaf** [comment]
I don't think it makes sense to let the user customize the action if we're opening a popup window. However, if the user could also set the popup to be a tab, then this could be useful.

Maybe there should also be an option for opening the Pinboard window at the same window which is being saved, then redirect back to it.

**Comment by fturcheti** [comment]
The first negative reaction to the window auto-closing just pinged at the AMO page: https://addons.mozilla.org/en-US/firefox/addon/pinboard-button/reviews/933873/

I published a quick fix, because closing the main browser window is something serious, but what do you think we should do about it? Simply keep things as they are right now, revert to redirecting home instead of closing or begin to investigate these options for a preferences page? I can see the value of each scenario you described above, and I know there are users for each one of these cases.

**Comment by fiatjaf** [comment]
Ok, what has happened there is that the code was set up to close the popup window (because a popup was being opened), but you've changed it to open a tab instead, so the code went and closed the entire window in which the tab was. Right? 

Now that you've changed that to close the tab everything is fixed and looks fine again to me.

I don't like the idea of redirecting to Pinboard, I very much prefer closing the popup/tab, but you prefer redirecting, so I don't know what to do. However if you're willing to implement an options page to control that then everything is solved and great.

**Comment by fturcheti** [comment]
> Ok, what has happened there is that the code was set up to close the popup window (because a popup was being opened), but you've changed it to open a tab instead, so the code went and closed the entire window in which the tab was. Right?

Not exactly. As we were opening a popup window, you wrote the code to close that window, and that seemed to be the right thing to do – what could go wrong? 

The problem is that Firefox has an option, hidden in `about:config`, to make all popups open as a new tab. In this case, the code to open a new popup window will open a new tab, and the code to close the window, will close the main browser window.

To fix this I changed the code to close the tab that sent the close message, because this would cover both cases: if it opened a popup window, closing the tab, the only tab within the window, would also close the window; if it opened a tab instead of a popup, it would close just that tab.

> I don't like the idea of redirecting to Pinboard, I very much prefer closing the popup/tab, but you prefer redirecting, so I don't know what to do. However if you're willing to implement an options page to control that then everything is solved and great.

OK. If I have some spare time in the near future, I'll try to implement this preferences page.

**Comment by fiatjaf** [comment]
> The problem is that Firefox has an option, hidden in `about:config`, to make all popups open as a new tab. In this case, the code to open a new popup window will open a new tab, and the code to close the window, will close the main browser window.

Uh, ok. Sorry about that.
